FROM node:22-alpine AS builder

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_BACK_END_API_PREFIX=/api
ARG VITE_FRONTEND_URL
ARG VITE_STRIPE_PUBLISHABLE_KEY
ARG VITE_SKIP_BACKEND_IMAGES=false

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_BACK_END_API_PREFIX=$VITE_BACK_END_API_PREFIX
ENV VITE_FRONTEND_URL=$VITE_FRONTEND_URL
ENV VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY
ENV VITE_SKIP_BACKEND_IMAGES=$VITE_SKIP_BACKEND_IMAGES

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]